[package]
name = "proof-helper"
version = "0.1.0"
edition = "2024"

[dependencies]
reth = { git = "https://github.com/paradigmxyz/reth.git", features = ["asm-keccak", "jemalloc"] } # Reth
op-reth = { git = "https://github.com/paradigmxyz/reth.git" } # Reth
reth-exex = { git = "https://github.com/paradigmxyz/reth.git" } # Execution Extensions
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth.git" } # Ethereum Node implementation
reth-tracing = { git = "https://github.com/paradigmxyz/reth.git" } # Logging
reth-trie = { git = "https://github.com/paradigmxyz/reth.git" }
reth-trie-db = { git = "https://github.com/paradigmxyz/reth.git" }
reth-db-api = { git = "https://github.com/paradigmxyz/reth.git" }
reth-execution-types = { git = "https://github.com/paradigmxyz/reth.git" }
reth-evm = { git = "https://github.com/paradigmxyz/reth.git" }
reth-stateless = { git = "https://github.com/paradigmxyz/reth.git" }
reth-codecs = { git = "https://github.com/paradigmxyz/reth.git" }
alloy-rlp = "0.3.12"

op-alloy-rpc-jsonrpsee = { version = "0.19.0", default-features = false }
op-alloy-network = { version = "0.19.0", default-features = false }

jsonrpsee = "0.26.0"
jsonrpsee-core = "0.26.0"
jsonrpsee-types = "0.26.0"

eyre = "0.6" # Easy error handling
futures-util = "0.3" # Stream utilities for consuming notifications
thiserror = "2.0"
async-trait = "0.1"
tokio = { version = "1.0", features = ["sync", "rt", "macros"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
aws-config = "1.1"
aws-sdk-dynamodb = "1.11"
aws-smithy-runtime-api = "1.1"
hex = "0.4"
rusqlite = { version = "0.31", features = ["bundled", "functions", "blob"] }

[dev-dependencies]
tempfile = "3.0"

# [patch."https://github.com/paradigmxyz/reth.git"]
# reth-trie = { path = "../reth/crates/trie/trie" }
# reth-trie-db = { path = "../reth/crates/trie/db" }
# reth = { path = "../reth/bin/reth" }
# op-reth = { path = "../reth/crates/optimism/bin" }
# reth-exex = { path = "../reth/crates/exex/exex" }
# reth-node-ethereum = { path = "../reth/crates/ethereum/node" }
# reth-tracing = { path = "../reth/crates/tracing" }
# reth-db-api = { path = "../reth/crates/storage/db-api" }
# reth-execution-types = { path = "../reth/crates/evm/execution-types" }
# reth-evm = { path = "../reth/crates/evm/evm" }
# reth-stateless = { path = "../reth/crates/stateless" }


# [patch.crates-io]
# alloy-trie = { path = "../trie" }
