[package]
name = "proof-helper"
version = "0.1.0"
edition = "2024"

[dependencies]
reth = { git = "https://github.com/paradigmxyz/reth.git", features = ["asm-keccak", "jemalloc"] } # Reth
op-reth = { git = "https://github.com/paradigmxyz/reth.git" } # Reth
reth-exex = { git = "https://github.com/paradigmxyz/reth.git" } # Execution Extensions
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth.git" } # Ethereum Node implementation
reth-tracing = { git = "https://github.com/paradigmxyz/reth.git" } # Logging
reth-trie = { git = "https://github.com/paradigmxyz/reth.git" }
reth-trie-db = { git = "https://github.com/paradigmxyz/reth.git" }
reth-db-api = { git = "https://github.com/paradigmxyz/reth.git" }
reth-execution-types = { git = "https://github.com/paradigmxyz/reth.git" }
reth-evm = { git = "https://github.com/paradigmxyz/reth.git" }
reth-stateless = { git = "https://github.com/paradigmxyz/reth.git" }
reth-trie-sparse = { git = "https://github.com/paradigmxyz/reth.git" }
reth-trie-common = { git = "https://github.com/paradigmxyz/reth.git" }
alloy-rlp = "0.3.12"

eyre = "0.6" # Easy error handling
futures-util = "0.3" # Stream utilities for consuming notifications
thiserror = "2.0"
async-trait = "0.1"
tokio = { version = "1.0", features = ["sync", "rt", "macros"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
aws-config = "1.1"
aws-sdk-dynamodb = "1.11"
aws-smithy-runtime-api = "1.1"
hex = "0.4"

[dev-dependencies]
tempfile = "3.0"